# Generated by Django 5.0.7 on 2024-07-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, to='shop.tag', verbose_name='Теги'),
        ),
    ]
