# Generated by Django 5.0.7 on 2024-07-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Товар-категория'},
        ),
    ]
