# Generated by Django 5.0.7 on 2024-07-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name': 'Товар-тег'},
        ),
    ]
